# Generated by Django 4.0.3 on 2022-05-30 07:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_room_partictipants'),
    ]

    operations = [
        migrations.RenameField(
            model_name='room',
            old_name='partictipants',
            new_name='participants',
        ),
    ]
